#### Initialisation


```{r}
library(tidyverse)
set.seed(42)
```

#### Task 1


```{r}

set.seed(42)
get_r_walk <- function(n = 1000, mean = 0, sd = 1) {
  y <- numeric(n)
  y <- 0 # initialising
  
  for (i in 2:n) {
    y[i] <- y[i - 1] + rnorm(1, mean = mean, sd = sd)
  }
  y
}

n <- 100
y <- get_r_walk(n, mean = 0, sd = 0.1)

cv <- sd(y)/mean(y)
cv
ggplot() +
  geom_line(aes(x = 1:n, y = y)) +
  labs(x = "Time", y = expression(y[t])) +
  theme_minimal()
```

#### Task 2

```{r}
get_un_loglin <- function(theta, mu = 0, sigma = 1, y) {
  un_dist <- theta^(sum(y) - 1) * exp(-length(y) * theta) *
    exp(-((log(theta) - mu) ^ 2) / (2 * sigma ^ 2))

  un_dist
}


```


```{r}
saints_goals <- c(1, 2, 2, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 3, 0, 1, 0, 3, 0, 1, 3, 0, 1, 4)

```


```{r}
S <- sum(saints_goals)
eta_prime <- log(0.8)
eta <- log(1.1)
n <- length(saints_goals)
mu <- 1
sigma <- 0.5

lr <- S * (eta_prime - eta) - n * (exp(eta_prime) - exp(eta)) - 
  ((eta_prime - mu) ^ 2 - (eta - mu) ^ 2)/(2 * sigma^2)

ar <- exp(lr)
ar
```

MCMC

```{r}
set.seed(42)
## Log unnormalised posterior for eta = log(theta)
## y    : vector of Poisson observations
## mu   : prior mean for eta
## sigma: prior sd for eta
logpost_eta <- function(eta, y, mu, sigma) {
  S <- sum(y)
  n <- length(y)
  # lp = S*eta - n*exp(eta) - (eta - mu)^2 / (2*sigma^2)
  S * eta - n * exp(eta) - (eta - mu)^2 / (2 * sigma^2)
}

## Metropolis sampler on eta = log(theta)
## proposal: eta' ~ N(eta_t, proposal_sd^2)
mh_pois_lognorm <- function(y,
                            mu,
                            sigma,
                            n_iter      = 10000,
                            proposal_sd = 0.2,  # 0.2^2 = 0.04
                            eta_init    = NULL) {
  if (is.null(eta_init)) {
    # Simple default: log of (mean(y)+small_offset) to avoid log(0)
    eta_init <- log(mean(y) + 0.1)
  }
  
  eta <- numeric(n_iter)
  eta[1] <- eta_init
  
  lp_curr <- logpost_eta(eta[1], y, mu, sigma)
  n_accept <- 0L
  
  for (t in 2:n_iter) {
    # Propose new eta'
    eta_prop <- rnorm(1, mean = eta[t - 1], sd = proposal_sd)
    
    # Log unnormalised posterior at proposal
    lp_prop <- logpost_eta(eta_prop, y, mu, sigma)
    
    # Log acceptance ratio
    log_r <- lp_prop - lp_curr
    
    # Accept/reject
    if (log(runif(1)) < log_r) {
      eta[t]   <- eta_prop
      lp_curr  <- lp_prop
      n_accept <- n_accept + 1L
    } else {
      eta[t] <- eta[t - 1]  # stay put
    }
  }
  
  theta <- exp(eta)
  
  list(
    eta         = eta,
    theta       = theta,
    accept_rate = n_accept / (n_iter - 1),
    mu          = mu,
    sigma       = sigma,
    proposal_sd = proposal_sd
  )
}
 
resp <- mh_pois_lognorm(y = saints_goals,
  mu = 1,
  sigma = 0.5,
  n_iter = 100,
  proposal_sd = 0.2,
    eta_init = mean(saints_goals)
  )
mean( resp$theta )
resp$accept_rate
```
