---
title: EM
format: html
---
* Initial Setup


```{r}
library(tidyverse)
set.seed(42)
```
* The missing data problem - Code


```{r}
x <- read_csv("data.csv")
x
n <- nrow(x)
n1 <- x |>
  filter(x2 != 0) |> nrow()  
n2 <- n - n1
x |>
  mutate(empty = x2 == 0) |>
  ggplot(aes(x = x1, y = x2)) +
  geom_point(aes(color = empty))

 ```
* function to estimate sigma


```{r}
sigma2_mle <- function(x) {
  n <- length(x)
  var(x) * (n - 1) / n
}
init_est <- x |>
  summarise(mu1 = mean(x1), mu2 = mean(x2), sigma21 = sigma2_mle(x1),
  sigma22 = sigma2_mle(x2), rho = cor(x1, x2)
  )
x |> filter(x2 != 0) |>
  summarise(mu1 = mean(x1), mu2 = mean(x2), sigma21 = sigma2_mle(x1),
  sigma22 = sigma2_mle(x2), rho = cor(x1, x2)
  )

```
* The E - M step


```{r}
e_step <- function(x1, params) {
  params$mu2 + params$rho * 
  (sqrt(params$sigma22) / sqrt(params$sigma21)) *
  (x1 - params$mu1)
}

m_step <- function(x1, x2, x2_e) {
  x2 <- c(x2, x2_e)
  tibble(
    mu1 = mean(x1),
    mu2 = mean(x2),
    sigma21 = sigma2_mle(x1),
    sigma22 = sigma2_mle(x2),
    rho = cor(x1, x2)
  )
} 
```

* E-M 


```{r}
no_iter = 10

params <- x |>
  summarise(mu1 = mean(x1), mu2 = mean(x2), sigma21 = sigma2_mle(x1),
  sigma22 = sigma2_mle(x2), rho = cor(x1, x2)
  )
params
m <- matrix(rep(0, no_iter * 5), nrow = 10)
colnames(m) = c("mu1", "mu2", "sigma21", "sigma22", "rho")
x_f <- x |> filter(x2 != 0)
x_e <- x |> filter(x2 == 0)
for (i in seq_len(no_iter)) {
  x2_e <- e_step(x_e$x1, params)
  params <- m_step(x$x1, x_f$x2, x2_e)
  m[i,] <- as.matrix(params)
}
m
```

